import { useState } from 'react'
import { Hash, X, Sparkles, RefreshCw } from 'lucide-react'
import { invoke } from '@tauri-apps/api/core'
import { PLATFORM_INFO } from '../stores/platformStore'
import { useAiStore } from '../stores/aiStore'
import { generateHashtagSuggestions, generateStandaloneTitle, generateStandaloneCaption, TONE_LABELS } from '../lib/publishCopyGenerator'
import type { ClipContext, GeneratedCopy, CopyTone } from '../lib/publishCopyGenerator'
import Tooltip from './Tooltip'

const TONE_TOOLTIPS: Record<string, string> = {
  direct_quote: 'Uses a direct quote from the clip',
  blame: 'Playful blame or call-out style',
  internal_thought: 'Inner monologue style caption',
  observation: 'Third-person description of the moment',
  minimal: 'Short and simple caption',
  punchy: 'Punchy, attention-grabbing caption',
  clean: 'Clean and polished caption',
  funny: 'Humorous caption with a comedic twist',
  hype: 'High-energy, hype-style caption',
  search: 'Optimized for search and discovery',
}

interface CaptionVariant {
  mode: string
  label: string
  text: string
}

interface BackendCaptions {
  captions: CaptionVariant[]
  hashtags: string[]
  source: 'free' | 'llm'
  casual: string
  funny: string
  hype: string
}

export interface PublishMetadata {
  title: string
  description: string
  hashtags: string[]
  visibility: 'public' | 'private' | 'unlisted'
}

// Platform-specific field configurations
const PLATFORM_FIELDS: Record<string, {
  hasTitle: boolean
  captionLabel: string
  captionMax: number
  titleMax: number
  hashtagLimit: number
}> = {
  tiktok:    { hasTitle: false, captionLabel: 'Caption',      captionMax: 2200, titleMax: 0,   hashtagLimit: 5 },
  youtube:   { hasTitle: false, captionLabel: 'Caption',      captionMax: 5000, titleMax: 100, hashtagLimit: 15 },
  instagram: { hasTitle: false, captionLabel: 'Caption',      captionMax: 2200, titleMax: 0,   hashtagLimit: 30 },
}

interface Props {
  platform: string
  metadata: PublishMetadata
  onChange: (m: PublishMetadata) => void
  /** Clip context for AI generation — if provided, shows Generate button */
  clipContext?: ClipContext
  /** Clip ID for backend caption generation */
  clipId?: string
}

// Sentinel description for BYOK tones not yet generated by AI
const AI_PENDING_PLACEHOLDER = '__ai_pending__'

export default function PublishComposer({ platform, metadata, onChange, clipContext, clipId }: Props) {
  const [tagInput, setTagInput] = useState('')
  const [variants, setVariants] = useState<GeneratedCopy[] | null>(null)
  const [selectedTone, setSelectedTone] = useState<CopyTone | null>(null)
  const [showSuggestions, setShowSuggestions] = useState(false)
  const [lastApplied, setLastApplied] = useState('')
  const [generating, setGenerating] = useState(false)
  const [genCount, setGenCount] = useState(0)
  const [usedFallback, setUsedFallback] = useState(false)
  const [loadingTone, setLoadingTone] = useState<string | null>(null)
  const aiStore = useAiStore()
  const fields = PLATFORM_FIELDS[platform] || PLATFORM_FIELDS.tiktok
  const info = PLATFORM_INFO[platform] || { name: platform, color: '#888' }

  // Defensive: hashtags may be undefined if backend omits the field after AI generation
  const hashtags = metadata.hashtags ?? []

  const update = (patch: Partial<PublishMetadata>) => onChange({ ...metadata, ...patch })

  const addHashtag = () => {
    const tag = tagInput.trim().replace(/^#/, '').replace(/\s+/g, '')
    if (!tag || hashtags.includes(tag)) return
    if (hashtags.length >= fields.hashtagLimit) return
    onChange({ ...metadata, hashtags: [...hashtags, tag] })
    setTagInput('')
  }

  const removeHashtag = (tag: string) => {
    update({ hashtags: hashtags.filter(t => t !== tag) })
  }

  /** Auto-generate a fresh set of context-aware hashtags in one click */
  const autoGenerateHashtags = () => {
    if (!clipContext) return
    console.log('[PublishComposer] autoGenerateHashtags — clipContext.game:', JSON.stringify(clipContext.game))
    const suggestions = generateHashtagSuggestions(clipContext, platform)
    // Group by relevance tier and shuffle within each tier for variety
    const tiered = new Map<number, typeof suggestions>()
    for (const s of suggestions) {
      const tier = Math.round(s.relevance * 10)  // bucket into 0.1 tiers
      if (!tiered.has(tier)) tiered.set(tier, [])
      tiered.get(tier)!.push(s)
    }
    // Shuffle within each tier
    const shuffled: typeof suggestions = []
    for (const tier of [...tiered.keys()].sort((a, b) => b - a)) {
      const group = tiered.get(tier)!
      for (let i = group.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1))
        ;[group[i], group[j]] = [group[j], group[i]]
      }
      shuffled.push(...group)
    }
    // Pick from shuffled suggestions up to platform limit
    const fresh: string[] = []
    for (const s of shuffled) {
      if (fresh.length >= fields.hashtagLimit) break
      if (!fresh.includes(s.tag)) fresh.push(s.tag)
    }
    // Replace existing hashtags with the fresh set
    update({ hashtags: fresh })
  }

  const descriptionWithTags = metadata.description +
    (hashtags.length > 0 ? '\n\n' + hashtags.map(t => `#${t}`).join(' ') : '')
  const charCount = descriptionWithTags.length

  return (
    <div className="space-y-3">
      {/* Platform badge */}
      <div className="flex items-center gap-2">
        <div className="w-5 h-5 rounded flex items-center justify-center text-[8px] font-bold shrink-0"
          style={{ background: `${info.color}20`, color: info.color }}>
          {PLATFORM_INFO[platform]?.icon || '?'}
        </div>
        <span className="text-xs text-slate-400">Preparing for {info.name}</span>
      </div>

      {/* AI Generate — single button, generates fresh each press */}
      {clipContext && (
        <div className="space-y-2">
          <div className="flex gap-2">
            <Tooltip text={variants ? 'Generate a new caption using a different approach' : 'Auto-generate captions for this clip'}>
            <button
              disabled={generating}
              onClick={async () => {
                setGenerating(true)
                const nextCount = genCount + 1
                setGenCount(nextCount)
                try {
                  // Use count-based seed that fits in u32 range (backend expects Option<u32>)
                  const seed = ((Date.now() % 1_000_000) * 1000 + nextCount) >>> 0

                  // Read fresh context — clipContext.title comes directly from Editor's
                  // title state (always current), metadata.title may be stale from last generation
                  const freshCtx: ClipContext = {
                    ...clipContext,
                    title: clipContext.title || metadata.title,
                  }
                  console.log('[PublishComposer] Generating captions — game:', JSON.stringify(freshCtx.game), '| title:', freshCtx.title)

                  // Generate a fresh title for each tone
                  const freshTitle = generateStandaloneTitle(freshCtx)

                  const isByok = aiStore.isByok()

                  // When BYOK is configured, skip free templates entirely — only use AI.
                  // Free templates are ONLY shown when no API key is set.
                  let allVariants: GeneratedCopy[] = []
                  setUsedFallback(false)

                  if (clipId) {
                    try {
                      const bc = await invoke<BackendCaptions>('generate_post_captions', {
                        clipId,
                        seed,
                        transcriptText: freshCtx.transcript || null,
                        currentTitle: clipContext.title || metadata.title || null,
                        currentGame: clipContext.game || null,
                        selectedMode: selectedTone || null,
                      })
                      const backendVariants: GeneratedCopy[] = bc.captions.map((c: CaptionVariant) => ({
                        title: clipContext.title || metadata.title,
                        description: c.text,
                        hashtags: [], // captions never carry hashtags
                        tone: c.mode as CopyTone,
                      }))

                      if (isByok && bc.source === 'llm') {
                        // BYOK + AI succeeded: populate ALL tone slots.
                        // The AI-generated tone gets its real text; others get a
                        // placeholder so buttons render — clicking them triggers
                        // an on-demand AI call for that specific tone.
                        const allTones: CopyTone[] = [
                          'punchy', 'clean', 'funny', 'hype', 'search', 'minimal',
                          'direct_quote', 'blame', 'internal_thought', 'observation',
                        ]
                        const aiToneMap = new Map(backendVariants.map(v => [v.tone, v]))
                        allVariants = allTones.map(tone => aiToneMap.get(tone) || {
                          title: clipContext.title || metadata.title,
                          description: AI_PENDING_PLACEHOLDER,
                          hashtags: [],
                          tone,
                        })
                      } else if (isByok && bc.source === 'free') {
                        // BYOK configured but AI failed/unavailable — fall back to templates
                        setUsedFallback(true)
                        allVariants = backendVariants
                      } else {
                        // Free mode: combine frontend templates + backend free captions
                        const frontendTones: CopyTone[] = [
                          'punchy', 'clean', 'funny', 'hype', 'search', 'minimal',
                          'direct_quote', 'blame', 'internal_thought', 'observation',
                        ]
                        const frontendVariants: GeneratedCopy[] = frontendTones.map(tone => ({
                          title: freshTitle,
                          description: generateStandaloneCaption(freshCtx, tone),
                          hashtags: [],
                          tone,
                        }))
                        allVariants = [...frontendVariants, ...backendVariants]
                      }
                    } catch {
                      // Backend call failed entirely — fall back to frontend templates
                      if (isByok) setUsedFallback(true)
                      const frontendTones: CopyTone[] = [
                        'punchy', 'clean', 'funny', 'hype', 'search', 'minimal',
                        'direct_quote', 'blame', 'internal_thought', 'observation',
                      ]
                      allVariants = frontendTones.map(tone => ({
                        title: freshTitle,
                        description: generateStandaloneCaption(freshCtx, tone),
                        hashtags: [],
                        tone,
                      }))
                    }
                  } else {
                    // No clipId — can only use frontend templates
                    const frontendTones: CopyTone[] = [
                      'punchy', 'clean', 'funny', 'hype', 'search', 'minimal',
                      'direct_quote', 'blame', 'internal_thought', 'observation',
                    ]
                    allVariants = frontendTones.map(tone => ({
                      title: freshTitle,
                      description: generateStandaloneCaption(freshCtx, tone),
                      hashtags: [],
                      tone,
                    }))
                  }

                  // Deduplicate by tone — first occurrence wins
                  const seen = new Set<string>()
                  const merged = allVariants.filter(v => {
                    if (seen.has(v.tone)) return false
                    seen.add(v.tone)
                    return true
                  })

                  setVariants(merged)
                  // Auto-apply captions and title — but NEVER touch hashtags.
                  // Hashtags have their own separate regenerate button.
                  // Skip placeholders (AI_PENDING_PLACEHOLDER) — only apply real content.
                  if (merged.length > 0) {
                    const realVariants = merged.filter(v => v.description !== AI_PENDING_PLACEHOLDER)
                    const preferred = selectedTone
                      ? realVariants.find(v => v.tone === selectedTone)
                      : null
                    const pick = preferred || realVariants[0] || merged[0]
                    if (pick.description !== AI_PENDING_PLACEHOLDER) {
                      onChange({ ...metadata, title: pick.title, description: pick.description })
                      setSelectedTone(pick.tone)
                      setLastApplied(pick.description)
                    }
                  }
                } finally {
                  setGenerating(false)
                }
              }}
              className="flex-1 flex items-center justify-center gap-1.5 px-3 py-2 bg-violet-600/20 border border-violet-500/40 rounded-lg text-xs text-violet-400 hover:bg-violet-600/30 transition-colors cursor-pointer disabled:opacity-50">
              {generating
                ? <><RefreshCw className="w-3.5 h-3.5 animate-spin" /> {genCount <= 1 ? 'Generating...' : 'Rerolling...'}</>
                : <><Sparkles className="w-3.5 h-3.5" /> {variants ? 'Reroll Captions' : 'Generate Captions'}</>
              }
            </button>
            </Tooltip>
          </div>

          {/* Tone variant selector */}
          {variants && variants.length > 0 && (
            <div className="flex gap-1 flex-wrap">
              {variants.map(v => {
                const tl = TONE_LABELS[v.tone]
                const active = selectedTone === v.tone
                const isPending = v.description === AI_PENDING_PLACEHOLDER
                const isLoading = loadingTone === v.tone
                return (
                  <Tooltip key={v.tone} text={isPending ? `Generate ${tl.label} caption via AI` : TONE_TOOLTIPS[v.tone] || `${tl.label} style caption`}>
                    <button
                      disabled={isLoading}
                      onClick={async () => {
                        const hasManualEdits = lastApplied && metadata.description !== lastApplied
                        if (hasManualEdits && !confirm('Replace your edits with this variant?')) return

                        if (isPending && clipId && clipContext) {
                          // On-demand AI generation for this tone
                          setLoadingTone(v.tone)
                          try {
                            const seed = ((Date.now() % 1_000_000) * 1000 + genCount) >>> 0
                            const bc = await invoke<BackendCaptions>('generate_post_captions', {
                              clipId,
                              seed,
                              transcriptText: clipContext.transcript || null,
                              currentTitle: clipContext.title || metadata.title || null,
                              currentGame: clipContext.game || null,
                              selectedMode: v.tone,
                            })
                            if (bc.captions.length > 0) {
                              const aiText = bc.captions[0].text
                              // Update this variant in-place
                              setVariants(prev => prev && prev.map(pv =>
                                pv.tone === v.tone ? { ...pv, description: aiText } : pv
                              ))
                              setSelectedTone(v.tone)
                              onChange({ ...metadata, title: v.title, description: aiText })
                              setLastApplied(aiText)
                            }
                          } catch (err) {
                            console.warn(`[PublishComposer] On-demand AI gen failed for ${v.tone}:`, err)
                          } finally {
                            setLoadingTone(null)
                          }
                        } else if (!isPending) {
                          setSelectedTone(v.tone)
                          onChange({ ...metadata, title: v.title, description: v.description })
                          setLastApplied(v.description)
                        }
                      }}
                      className={`px-2 py-1 rounded text-[10px] font-medium border cursor-pointer transition-colors ${
                        active
                          ? 'bg-violet-600/20 text-violet-400 border-violet-500/40'
                          : isPending
                            ? 'bg-surface-900 text-slate-600 border-surface-700 hover:text-slate-400 border-dashed'
                            : 'bg-surface-900 text-slate-500 border-surface-600 hover:text-white'
                      } ${isLoading ? 'opacity-50' : ''}`}>
                      {isLoading ? <RefreshCw className="w-2.5 h-2.5 animate-spin inline mr-0.5" /> : null}
                      {tl.emoji} {tl.label}
                    </button>
                  </Tooltip>
                )
              })}
            </div>
          )}

          {/* Fallback notice */}
          {usedFallback && (
            <p className="text-[10px] text-amber-400/80 mt-1">
              Provider unavailable, used Free mode instead.
            </p>
          )}
        </div>
      )}

      {/* Caption */}
      <div>
        <div className="flex justify-between mb-1">
          <label className="text-xs text-slate-400">{fields.captionLabel}</label>
          <span className={`text-[9px] font-mono ${charCount > fields.captionMax ? 'text-red-400' : 'text-slate-600'}`}>
            {charCount}/{fields.captionMax}
          </span>
        </div>
        <textarea value={metadata.description} onChange={e => update({ description: e.target.value })}
          placeholder={`Write your ${fields.captionLabel.toLowerCase()}...`}
          rows={3}
          className="w-full px-3 py-2 bg-surface-900 border border-surface-600 rounded-lg text-white text-sm focus:outline-none focus:border-violet-500 placeholder-slate-500 resize-none" />
      </div>

      {/* Hashtags */}
      <div>
        <div className="flex justify-between mb-1">
          <label className="text-xs text-slate-400">Hashtags</label>
          <span className={`text-[9px] ${hashtags.length >= fields.hashtagLimit ? 'text-amber-400' : 'text-slate-600'}`}>{hashtags.length}/{fields.hashtagLimit}{hashtags.length >= fields.hashtagLimit ? ' (max)' : ''}</span>
        </div>

        {/* Current tags */}
        {hashtags.length > 0 && (
          <div className="flex flex-wrap gap-1.5 mb-2">
            {hashtags.map(tag => (
              <span key={tag} className="flex items-center gap-1 px-2 py-0.5 bg-violet-600/15 text-violet-400 text-[10px] rounded-full border border-violet-500/30">
                #{tag}
                <button onClick={() => removeHashtag(tag)} className="hover:text-red-400 cursor-pointer">
                  <X className="w-2.5 h-2.5" />
                </button>
              </span>
            ))}
          </div>
        )}

        {/* Input + suggest button */}
        <div className="flex gap-1.5">
          <div className="flex-1 relative">
            <Hash className="absolute left-2 top-1/2 -translate-y-1/2 w-3 h-3 text-slate-500" />
            <input type="text" value={tagInput}
              onChange={e => setTagInput(e.target.value)}
              onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); addHashtag() } }}
              placeholder="Add hashtag..."
              className="w-full pl-6 pr-2 py-1.5 bg-surface-900 border border-surface-600 rounded text-white text-xs focus:outline-none focus:border-violet-500 placeholder-slate-500" />
          </div>
          <Tooltip text={hashtags.length >= fields.hashtagLimit ? `Hashtag limit reached (${fields.hashtagLimit} max)` : 'Add a custom hashtag'}>
            <button type="button" onClick={addHashtag} disabled={!tagInput.trim() || hashtags.length >= fields.hashtagLimit}
              className="px-2 py-1 bg-surface-800 border border-surface-600 rounded text-xs text-slate-400 hover:text-white disabled:opacity-30 disabled:cursor-not-allowed cursor-pointer">
              {hashtags.length >= fields.hashtagLimit ? 'Full' : 'Add'}
            </button>
          </Tooltip>
          {clipContext && (
            <>
              <Tooltip text="Auto-generate context-aware hashtags (replaces current)">
                <button onClick={autoGenerateHashtags}
                  className="px-2 py-1 bg-violet-600 hover:bg-violet-500 border border-violet-500 rounded text-xs text-white cursor-pointer transition-colors">
                  <Sparkles className="w-3 h-3" />
                </button>
              </Tooltip>
              <Tooltip text={showSuggestions ? 'Hide suggestions' : 'Browse hashtag suggestions'}>
                <button onClick={() => setShowSuggestions(s => !s)}
                  className={`px-2 py-1 border rounded text-xs cursor-pointer transition-colors ${
                    showSuggestions ? 'bg-violet-600/20 text-violet-400 border-violet-500/40' : 'bg-surface-800 text-slate-400 border-surface-600 hover:text-white'
                  }`}>
                  &hellip;
                </button>
              </Tooltip>
            </>
          )}
        </div>

        {/* Smart suggestions */}
        {showSuggestions && clipContext && (() => {
          const suggestions = generateHashtagSuggestions(clipContext, platform)
            .filter(s => !hashtags.includes(s.tag))
            .slice(0, 20)
          const categories = [...new Set(suggestions.map(s => s.category))]

          return (
            <div className="mt-2 p-2 bg-surface-900 border border-surface-600 rounded-lg space-y-2 max-h-36 overflow-y-auto">
              <p className="text-[9px] text-slate-500">Click to add — sorted by relevance</p>
              {categories.map(cat => {
                const catSuggestions = suggestions.filter(s => s.category === cat)
                if (catSuggestions.length === 0) return null
                return (
                  <div key={cat}>
                    <p className="text-[8px] text-slate-600 uppercase tracking-wider mb-0.5">{cat}</p>
                    <div className="flex flex-wrap gap-1">
                      {catSuggestions.map(s => (
                        <button key={s.tag}
                          onClick={() => {
                            if (hashtags.length < fields.hashtagLimit && !hashtags.includes(s.tag)) {
                              update({ hashtags: [...hashtags, s.tag] })
                            }
                          }}
                          disabled={hashtags.length >= fields.hashtagLimit}
                          className="px-1.5 py-0.5 bg-surface-800 text-[9px] text-slate-400 rounded border border-surface-600 hover:text-violet-400 hover:border-violet-500/40 cursor-pointer disabled:opacity-30 transition-colors">
                          #{s.tag}
                        </button>
                      ))}
                    </div>
                  </div>
                )
              })}
            </div>
          )
        })()}
      </div>

      {/* Visibility (YouTube) */}
      {fields.hasTitle && (
        <div>
          <label className="text-xs text-slate-400 mb-1 block">Visibility</label>
          <div className="flex gap-1.5">
            {(['public', 'unlisted', 'private'] as const).map(v => (
              <button key={v} onClick={() => update({ visibility: v })}
                className={`flex-1 px-2 py-1.5 rounded text-[10px] font-medium border cursor-pointer transition-colors capitalize ${
                  metadata.visibility === v
                    ? 'bg-violet-600/20 text-violet-400 border-violet-500/40'
                    : 'bg-surface-900 text-slate-500 border-surface-600 hover:text-white'
                }`}>
                {v}
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}
