//! TikTok-ready post caption generation.
//!
//! Strict multi-mode system: 5 independent modes × GameType style.
//! Each caption is generated by: `generate_caption(event_summary, mode, game_type)`.
//!
//! Modes: DirectQuote, InternalThought, Blame, Observation, Minimal.
//! GameTypes: FPS, Horror, Cozy, Social, Generic.
//!
//! Every caption references what happened.  No fabricated outcomes, no clickbait.

use crate::pipeline::CandidateClip;
use crate::error::AppError;
use crate::detection::Platform;

// ═══════════════════════════════════════════════════════════════════
//  Output
// ═══════════════════════════════════════════════════════════════════

/// One caption per mode, labeled by mode name.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct PostCaptions {
    /// All generated captions, one per mode.
    pub captions: Vec<CaptionVariant>,
    pub hashtags: Vec<String>,
    /// Which system generated these: "free" or "llm".
    #[serde(default = "default_source")]
    pub source: String,

    // Legacy fields — populated from the first 3 captions for backward compat.
    pub casual: String,
    pub funny: String,
    pub hype: String,
}

fn default_source() -> String { "free".into() }

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CaptionVariant {
    /// Which mode generated this caption.
    pub mode: String,
    /// Human-readable mode label for the UI.
    pub label: String,
    /// The caption text.
    pub text: String,
}

// ═══════════════════════════════════════════════════════════════════
//  GameType detection
// ═══════════════════════════════════════════════════════════════════

/// Game type — determines wording style, phrasing patterns, and
/// blame targets across every caption mode.
///
/// | GameType | Style               | Vocab                          |
/// |----------|---------------------|--------------------------------|
/// | FPS      | Competitive, fast   | "pushed", "dropped", "one-tap" |
/// | Horror   | Dread, survival     | "the dark", "behind me"        |
/// | Cozy     | Chaotic, wholesome  | "whoops", "the kitchen"        |
/// | Social   | Group dynamics      | "the team", "whose fault"      |
/// | Generic  | Neutral streamer    | plain, no genre flavor         |
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GameType {
    /// FPS, battle royale, competitive PvP.
    FPS,
    /// Horror, jumpscare-heavy, survival horror.
    Horror,
    /// Cozy games, cooking sims, chaotic physics games.
    Cozy,
    /// Party games, social deduction, co-op chaos.
    Social,
    /// Anything that doesn't clearly fit above.
    Generic,
}

/// Backward-compat alias — existing code that references `Tone` still compiles.
pub type Tone = GameType;

/// Detect game type from tags, transcript, and signal scores.
///
/// Checks (in priority order):
///   1. Tags that strongly indicate a genre
///   2. Transcript style (genre-specific vocabulary)
///   3. Signal mix (audio-heavy = action, speech-heavy = social)
pub fn detect_game_type(
    tags: &[String],
    transcript: Option<&str>,
    audio_score: f64,
    speech_score: f64,
    scene_score: f64,
) -> GameType {
    let has = |t: &str| tags.iter().any(|x| x.to_lowercase().contains(t));

    // ── Tag-based (strongest signal) ──

    // Horror indicators
    if has("jumpscare") || has("scare") {
        return GameType::Horror;
    }
    if has("ambush") && has("panic") && !has("fight") {
        return GameType::Horror;
    }

    // FPS/action indicators
    if has("fight") || has("kill") || has("headshot") || has("snipe") {
        return GameType::FPS;
    }
    if has("ambush") && has("fight") {
        return GameType::FPS;
    }

    // Cozy/funny indicators
    if has("crash") || has("explosion") && has("celebration") {
        return GameType::Cozy;
    }

    // Social indicators
    if has("reaction") && has("hype") && speech_score > audio_score {
        return GameType::Social;
    }

    // ── Transcript-based ──
    if let Some(text) = transcript {
        let lower = text.to_lowercase();
        if lower.contains("scared") || lower.contains("terrified")
            || lower.contains("behind you") || lower.contains("dont look")
        {
            return GameType::Horror;
        }
        if lower.contains("whose fault") || lower.contains("blame")
            || lower.contains("you did this") || lower.contains("team")
            || lower.contains("why did you") || lower.contains("together")
        {
            return GameType::Social;
        }
        if lower.contains("kitchen") || lower.contains("recipe")
            || lower.contains("oops") || lower.contains("whoops")
            || lower.contains("mess") || lower.contains("broke")
        {
            return GameType::Cozy;
        }
    }

    // ── Signal mix ──
    if audio_score > 0.7 && scene_score > 0.5 && speech_score < 0.4 {
        return GameType::FPS;
    }
    if speech_score > 0.6 && audio_score < 0.5 {
        return GameType::Social;
    }

    GameType::Generic
}

/// Backward-compat wrapper — calls `detect_game_type`.
fn classify_tone(
    tags: &[String], transcript: Option<&str>,
    audio_score: f64, speech_score: f64, scene_score: f64,
) -> GameType {
    detect_game_type(tags, transcript, audio_score, speech_score, scene_score)
}

impl GameType {
    /// Human-readable label for the LLM prompt.
    pub fn label(self) -> &'static str {
        match self {
            GameType::FPS     => "FPS / competitive shooter",
            GameType::Horror  => "horror / survival",
            GameType::Cozy    => "cozy / chaotic casual",
            GameType::Social  => "social / party / co-op",
            GameType::Generic => "general gaming",
        }
    }
}

// ═══════════════════════════════════════════════════════════════════
//  Event summary — public preprocessing step
// ═══════════════════════════════════════════════════════════════════
//
//  Generates a 1-sentence description of what happened in the clip.
//  This is the foundation that all captions are built on.
//
//  Priority:
//    1. Transcript action + tag context  ("missed the shot during the fight")
//    2. Compound tag synthesis           ("got ambushed and panicked")
//    3. Single event + tone              ("something came out of the dark")
//    4. Tone-only fallback               ("got outplayed")

/// Generate a 1-sentence event summary from all available clip signals.
///
/// This is the preprocessing step that caption generation depends on.
/// The summary describes WHAT HAPPENED — not the reaction, not the vibe.
///
/// # Examples
///
/// | Transcript             | Tags                | Output                                   |
/// |------------------------|---------------------|------------------------------------------|
/// | "I missed that shot"   | fight, frustration  | "missed the shot and lost the fight"     |
/// | "oh god no"            | ambush, panic       | "got ambushed and completely panicked"   |
/// | (none)                 | fight, celebration  | "won the fight barely"                   |
/// | "what just happened"   | shock               | "something unexpected happened"          |
pub fn generate_event_summary(clip: &CandidateClip) -> String {
    let event = primary_event(&clip.tags);
    let tone = classify_tone(
        &clip.tags,
        clip.transcript_excerpt.as_deref(),
        clip.score_breakdown.audio_score,
        clip.score_breakdown.speech_score,
        clip.score_breakdown.scene_score,
    );
    let seed = clip.start_time as usize;

    // 1. Try transcript-enhanced summary
    if let Some(summary) = transcript_action_summary(
        clip.transcript_excerpt.as_deref(),
        event,
        &clip.tags,
        tone,
    ) {
        return summary;
    }

    // 2. Fall back to tag-based synthesis
    synthesize_event(event, tone, &clip.tags, seed)
}

/// Extract action-level intent from the transcript and combine with event context.
///
/// Returns None if the transcript is just filler/exclamations with no
/// recoverable action (e.g. "oh no", "what the hell").
fn transcript_action_summary(
    transcript: Option<&str>,
    event: Option<&str>,
    tags: &[String],
    _tone: Tone,
) -> Option<String> {
    let text = transcript?;
    let lower = text.to_lowercase();
    let words: Vec<&str> = lower.split_whitespace().collect();
    if words.len() < 3 { return None; }

    // Match action keywords that describe what happened (not reactions).
    // These are verbs/phrases a streamer says that reveal the actual event.
    let action = match () {
        _ if lower.contains("missed") && lower.contains("shot")
            => Some("missed the shot"),
        _ if lower.contains("missed")
            => Some("missed the play"),
        _ if lower.contains("whiffed") || lower.contains("whiff")
            => Some("whiffed completely"),
        _ if lower.contains("choked")
            => Some("choked at the worst time"),
        _ if lower.contains("died") || lower.contains("i'm dead")
            => Some("died"),
        _ if lower.contains("killed") && lower.contains("me")
            => Some("got killed"),
        _ if lower.contains("got him") || lower.contains("got them")
            => Some("got the kill"),
        _ if lower.contains("killed him") || lower.contains("killed it")
            => Some("landed the kill"),
        _ if lower.contains("stuck") || lower.contains("trapped")
            => Some("got trapped"),
        _ if lower.contains("fell") || lower.contains("falling")
            => Some("fell"),
        _ if lower.contains("ran") || lower.contains("running") || lower.contains("run")
            => Some("had to run for it"),
        _ if lower.contains("lost")
            => Some("lost it"),
        _ if lower.contains("won") || lower.contains("clutch")
            => Some("clutched it"),
        _ if lower.contains("broke") || lower.contains("broken")
            => Some("everything broke"),
        _ if lower.contains("explod") || lower.contains("blew up") || lower.contains("blown")
            => Some("got blown up"),
        _ if lower.contains("scared") || lower.contains("terrif")
            => Some("got scared"),
        _ if lower.contains("jumped") && !lower.contains("jumped in")
            => Some("got jumpscared"),
        _ if lower.contains("behind") && (lower.contains("you") || lower.contains("me"))
            => Some("something was right behind them"),
        _ if lower.contains("hit") && lower.contains("me")
            => Some("got hit out of nowhere"),
        _ if lower.contains("lag") || lower.contains("froze")
            => Some("froze at the worst moment"),
        _ if lower.contains("messed up") || lower.contains("screwed")
            => Some("messed up bad"),
        _ if lower.contains("forgot")
            => Some("forgot what to do"),
        _ => None,
    };

    let action = action?;

    // Combine action with tag-based context
    let has = |t: &str| tags.iter().any(|x| x == t);

    let combined = match event {
        Some("fight") if has("frustration") =>
            format!("{} and lost the fight", action),
        Some("fight") if has("celebration") =>
            format!("{} but won the fight anyway", action),
        Some("fight") if has("panic") =>
            format!("{} and the fight went sideways", action),
        Some("fight") =>
            format!("{} during the fight", action),
        Some("ambush") | Some("jumpscare") =>
            format!("{} after getting ambushed", action),
        Some("panic") =>
            format!("{} and panicked", action),
        Some("frustration") =>
            format!("{} and lost it", action),
        Some("clutch") | Some("celebration") =>
            format!("{} but somehow survived", action),
        _ => action.to_string(),
    };

    Some(combined)
}

// ═══════════════════════════════════════════════════════════════════
//  Public API
// ═══════════════════════════════════════════════════════════════════

/// Generate captions for a pipeline clip (deterministic — used during analysis).
pub fn generate(clip: &CandidateClip) -> PostCaptions {
    generate_with_seed(clip, 0)
}

/// Generate captions with an explicit seed (different seed = different output).
pub fn generate_with_seed(clip: &CandidateClip, seed: u32) -> PostCaptions {
    let event = primary_event(&clip.tags);
    let tone = classify_tone(
        &clip.tags,
        clip.transcript_excerpt.as_deref(),
        clip.score_breakdown.audio_score,
        clip.score_breakdown.speech_score,
        clip.score_breakdown.scene_score,
    );
    let s = mix_seed(clip.start_time as usize, seed);

    // Use the clip's pre-computed event summary if available,
    // otherwise generate one inline.
    let event_summary = clip.event_summary.clone()
        .unwrap_or_else(|| generate_event_summary(clip));

    let ctx = CaptionCtx {
        event_summary,
        quote: strong_quote(clip.transcript_excerpt.as_deref()),
        game_type: tone,
        seed: s,
    };
    let hashtags = build_hashtags(&clip.tags, ctx.game_type);
    build_variants(ctx, hashtags)
}

pub fn generate_from_parts(
    tags: &[String],
    transcript: Option<&str>,
    _title: &str,
    start_time: f64,
    audio_score: f64,
    speech_score: f64,
    scene_score: f64,
    seed: u32,
) -> PostCaptions {
    let event = primary_event(tags);
    let tone = classify_tone(tags, transcript, audio_score, speech_score, scene_score);
    let s = mix_seed(start_time as usize, seed);

    // Try transcript-enhanced summary, fall back to tag-based
    let event_summary = transcript_action_summary(transcript, event, tags, tone)
        .unwrap_or_else(|| synthesize_event(event, tone, tags, s));

    let ctx = CaptionCtx {
        event_summary,
        quote: strong_quote(transcript),
        game_type: tone,
        seed: s,
    };
    let hashtags = build_hashtags(tags, ctx.game_type);
    build_variants(ctx, hashtags)
}

pub fn generate_all(clips: &mut [CandidateClip]) {
    for clip in clips.iter_mut() {
        let captions = generate(clip);
        clip.post_captions = Some(captions);
    }
}

// ═══════════════════════════════════════════════════════════════════
//  Strict multi-mode caption system
// ═══════════════════════════════════════════════════════════════════
//
//  Architecture:
//    for mode in [DirectQuote, InternalThought, Blame, Observation, Minimal]:
//        generate_caption(event_summary, mode)
//
//  Each mode is a standalone function that builds its output FROM
//  the event_summary.  No shared templates.  No pre-written phrase
//  pools.  Every caption names what happened.
//
//  Global rules:
//    - MUST reference event_summary (the event is the caption's core)
//    - No generic phrases ("this happened", "caught on stream")
//    - Short and natural (under 15 words)

/// Everything a mode needs to produce one caption.
///
/// Prompt structure per caption:
///   1. event_summary  — what happened (required core)
///   2. base rules     — must reference event, no generic phrases, short
///   3. mode rules     — DirectQuote/Blame/InternalThought/Observation/Minimal
///   4. game_type      — FPS/Horror/Cozy/Social/Generic style overlay
struct CaptionCtx {
    /// Required: what happened in the clip ("missed the shot and lost the fight").
    event_summary: String,
    /// Optional: cleaned transcript quote from the streamer.
    quote: Option<String>,
    /// Game type — determines wording style, phrasing, and blame targets.
    game_type: GameType,
    /// Deterministic seed for structural variety on reroll.
    seed: usize,
}

// ═══════════════════════════════════════════════════════════════════
//  Event synthesis: tags + tone + event → concrete action sentence
// ═══════════════════════════════════════════════════════════════════
//
//  This is the critical step that makes captions specific.
//  Instead of "chaos" or "timing", we produce:
//    "got ambushed and panicked"
//    "the kitchen caught fire"
//    "teammate sold the round"

/// Build a concrete event summary from available signals.
/// Returns a short action phrase (no "i", no quotes — just what happened).
fn synthesize_event(
    event: Option<&str>,
    tone: Tone,
    tags: &[String],
    seed: usize,
) -> String {
    let has = |t: &str| tags.iter().any(|x| x == t);

    // ── Compound tag combinations → specific events ──
    if has("fight") && has("panic") {
        return pick(seed, &[
            "fight broke out and went wrong fast",
            "got into a fight and panicked",
            "the fight spiraled out of control",
        ]);
    }
    if has("fight") && has("celebration") {
        return pick(seed, &[
            "won the fight barely",
            "clutched the fight at the last second",
            "somehow survived that fight",
        ]);
    }
    if has("fight") && has("frustration") {
        return pick(seed, &[
            "lost that fight and it stung",
            "the fight went wrong and it hurt",
            "got outplayed in the fight",
        ]);
    }
    if (has("jumpscare") || has("ambush")) && has("panic") {
        return pick(seed, &[
            "got ambushed and completely panicked",
            "something appeared out of nowhere",
            "got jumped and had zero time to react",
        ]);
    }
    if (has("jumpscare") || has("ambush")) && has("shock") {
        return pick(seed, &[
            "got scared out of nowhere",
            "something jumped out at the worst time",
            "the jumpscare hit with no warning",
        ]);
    }

    // ── Single event + tone → specific actions ──
    if let Some(ev) = event {
        return match (ev, tone) {
            ("ambush", GameType::Horror)  => pick(seed, &[
                "something came out of the dark",
                "turned a corner and regretted it",
                "heard a noise and it was already too late",
            ]),
            ("ambush", _)             => pick(seed, &[
                "got rushed with no warning",
                "enemy appeared out of nowhere",
                "got caught completely off guard",
            ]),
            ("fight", GameType::FPS)  => pick(seed, &[
                "took a fight and got dropped instantly",
                "pushed and it went wrong immediately",
                "the gunfight lasted about one second",
            ]),
            ("fight", _)              => pick(seed, &[
                "a fight broke out suddenly",
                "things got heated fast",
                "the fight went sideways",
            ]),
            ("clutch", _)             => pick(seed, &[
                "barely survived at the last second",
                "pulled it off with almost nothing left",
                "clutched it when it looked impossible",
            ]),
            ("panic", GameType::Cozy)     => pick(seed, &[
                "the kitchen caught fire",
                "everything went wrong at once",
                "the whole plan fell apart instantly",
            ]),
            ("panic", GameType::Social)   => pick(seed, &[
                "the whole group panicked at once",
                "someone made a bad call and everyone suffered",
                "the team fell apart in seconds",
            ]),
            ("panic", _)              => pick(seed, &[
                "everything went wrong at the same time",
                "panic set in and nothing worked",
                "lost control of the situation completely",
            ]),
            ("frustration", _)        => pick(seed, &[
                "nothing went right",
                "missed the obvious play",
                "made the wrong call and paid for it",
            ]),
            ("shock" | "disbelief", _) => pick(seed, &[
                "something unexpected happened",
                "nobody saw that coming",
                "it came completely out of nowhere",
            ]),
            ("hype" | "reaction", _)   => pick(seed, &[
                "something big happened and the reaction was instant",
                "the moment hit and the energy shifted",
                "it happened and there was no holding back",
            ]),
            ("explosion", _)          => pick(seed, &[
                "everything blew up with no warning",
                "an explosion hit out of nowhere",
                "it all went up in flames instantly",
            ]),
            _ => pick(seed, &[
                "something happened that nobody expected",
                "the moment came out of nowhere",
            ]),
        };
    }

    // ── Tone-only fallback ──
    match tone {
        GameType::Horror  => pick(seed, &["something scary happened", "got scared"]),
        GameType::Cozy    => pick(seed, &["things went chaotic", "the plan fell apart"]),
        GameType::Social  => pick(seed, &["the group fell apart", "someone messed up"]),
        GameType::FPS => pick(seed, &["got outplayed", "the play went wrong"]),
        GameType::Generic => pick(seed, &["something happened", "a moment hit"]),
    }
}

fn pick(seed: usize, opts: &[&str]) -> String {
    opts[seed % opts.len()].to_string()
}

// ═══════════════════════════════════════════════════════════════════
//  Modes
// ═══════════════════════════════════════════════════════════════════

#[derive(Clone, Copy, PartialEq, Eq)]
enum Mode {
    /// Spoken reaction — raw words someone would say in this moment.
    DirectQuote,
    /// External fault assignment — frustrated, ironic, pointing fingers.
    Blame,
    /// First-person reflection — inner monologue, personal, after-the-fact.
    InternalThought,
    /// Third-person description — detached, dry, documentary.
    Observation,
    /// 1–3 word gut punch — extracted from the event itself.
    Minimal,
}

const MODES: [Mode; 5] = [
    Mode::DirectQuote, Mode::Blame, Mode::InternalThought,
    Mode::Observation, Mode::Minimal,
];

fn mix_seed(base: usize, seed: u32) -> usize {
    let s = base.wrapping_mul(2654435761).wrapping_add(seed as usize);
    s ^ (s >> 16)
}

// ═══════════════════════════════════════════════════════════════════
//  Caption dispatch
// ═══════════════════════════════════════════════════════════════════

/// Generate one caption for a specific mode.
///
/// `event_summary` is the required foundation — every output must
/// reference what happened.  Each mode applies a unique transformation.
fn generate_caption(mode: Mode, ctx: &CaptionCtx) -> String {
    let text = match mode {
        Mode::DirectQuote     => gen_direct_quote(ctx),
        Mode::Blame           => gen_blame(ctx),
        Mode::InternalThought => gen_internal_thought(ctx),
        Mode::Observation     => gen_observation(ctx),
        Mode::Minimal         => gen_minimal(ctx),
    };

    // Global rule: reject generics, retry once with shifted seed
    if is_generic(&text) || text.to_lowercase() == ctx.event_summary.to_lowercase() {
        let retry = CaptionCtx {
            seed: ctx.seed.wrapping_add(9973),
            event_summary: ctx.event_summary.clone(),
            quote: ctx.quote.clone(),
            game_type: ctx.game_type,
        };
        return match mode {
            Mode::DirectQuote     => gen_direct_quote(&retry),
            Mode::Blame           => gen_blame(&retry),
            Mode::InternalThought => gen_internal_thought(&retry),
            Mode::Observation     => gen_observation(&retry),
            Mode::Minimal         => gen_minimal(&retry),
        };
    }

    text
}

fn is_generic(text: &str) -> bool {
    let lower = text.to_lowercase();
    GENERIC_PHRASES.iter().any(|p| lower.contains(p))
}

// ═══════════════════════════════════════════════════════════════════
//  Mode: DirectQuote — spoken reaction
// ═══════════════════════════════════════════════════════════════════
//
//  What someone would literally say in this moment.
//  If transcript quote exists: use it verbatim — that IS the caption.
//  If not: construct a spoken exclamation from the event_summary.
//  No commentary, no framing, no "i said". Just the words.

fn gen_direct_quote(ctx: &CaptionCtx) -> String {
    // Real speech → the quote IS the caption
    if let Some(ref q) = ctx.quote {
        // Vary the framing on reroll using seed
        let framings = [
            format!("\"{}\"", q),
            format!("\"{}\" — live", q),
            format!("\"{}\" — on stream", q),
        ];
        return framings[ctx.seed % framings.len()].clone();
    }

    // No transcript — construct what someone would say.
    // GameType determines the spoken style: FPS players react differently
    // than horror players or cozy streamers.
    let ev = &ctx.event_summary;
    let core = first_n_words(ev, 5);

    match ctx.game_type {
        GameType::FPS    => {
            let opts = [format!("\"no shot— {}\"", core), format!("\"how did {}\"", core)];
            opts[ctx.seed % opts.len()].clone()
        }
        GameType::Horror => {
            let opts = [format!("\"oh god— {}\"", core), format!("\"nope— {}\"", core)];
            opts[ctx.seed % opts.len()].clone()
        }
        GameType::Cozy   => {
            let opts = [format!("\"wait how did {}\"", core), format!("\"why did {}\"", core)];
            opts[ctx.seed % opts.len()].clone()
        }
        GameType::Social => {
            let opts = [format!("\"who— {}\"", core), format!("\"okay so {}\"", core)];
            opts[ctx.seed % opts.len()].clone()
        }
        GameType::Generic => {
            let opts = [format!("\"i just {}\"", core), format!("\"wait— {}\"", core), format!("\"{}\"", core)];
            opts[ctx.seed % opts.len()].clone()
        }
    }
}

// ═══════════════════════════════════════════════════════════════════
//  Mode: InternalThought — first-person reflection
// ═══════════════════════════════════════════════════════════════════
//
//  Inner monologue. Always "i". Reflective, personal, after-the-fact.
//  The thought directly names what happened — it's not vague.
//  Never detached. Never third-person. Never generic.
//
//  Sentence built by wrapping event_summary in a reflective frame.
//  Tone determines the emotional color of the reflection.

fn gen_internal_thought(ctx: &CaptionCtx) -> String {
    let ev = &ctx.event_summary;

    // If there's a quote, contrast internal vs external state.
    // Keep leading words short — captions_are_short test asserts ≤16 words total,
    // and a mid-length transcript quote adds 8+ on its own.
    if let Some(ref q) = ctx.quote {
        let opts = [
            format!("inside: calm. out loud: \"{}\"", q),
            format!("wanted to say nothing. said: \"{}\"", q),
            format!("told myself i wouldn't. then: \"{}\"", q),
        ];
        return opts[ctx.seed % opts.len()].clone();
    }

    // Tone determines the reflective frame around the event
    match ctx.game_type {
        GameType::Horror  => {
            let opts = [format!("i'm still not over when {}", ev), format!("i can't stop thinking about when {}", ev)];
            opts[ctx.seed % opts.len()].clone()
        }
        GameType::Cozy    => {
            let opts = [format!("i genuinely did not expect {}", ev), format!("nobody prepared me for {}", ev)];
            opts[ctx.seed % opts.len()].clone()
        }
        GameType::Social  => {
            let opts = [format!("i should have seen it coming. {}", ev), format!("i trusted them. then {}", ev)];
            opts[ctx.seed % opts.len()].clone()
        }
        GameType::FPS => {
            let opts = [format!("i keep replaying it. {}", ev), format!("i still think about when {}", ev)];
            opts[ctx.seed % opts.len()].clone()
        }
        GameType::Generic => {
            let opts = [
                format!("i knew {} was going to happen and i still wasn't ready", ev),
                format!("part of me saw {} coming. the rest of me didn't care", ev),
            ];
            opts[ctx.seed % opts.len()].clone()
        }
    }
}

// ═══════════════════════════════════════════════════════════════════
//  Mode: Blame — external fault assignment
// ═══════════════════════════════════════════════════════════════════
//
//  Points fingers. Frustrated. Ironic.
//  Never "i" as subject — always blaming something external.
//  Structure: [event happened] + [fault assigned].
//  Tone determines who or what gets blamed.

fn gen_blame(ctx: &CaptionCtx) -> String {
    let ev = &ctx.event_summary;

    // Quote path: speech followed by blame
    if let Some(ref q) = ctx.quote {
        let opts = [
            format!("\"{}\" — and whose fault was that", q),
            format!("\"{}\" — blame the game not me", q),
            format!("\"{}\" — someone needs to answer for this", q),
        ];
        return opts[ctx.seed % opts.len()].clone();
    }

    // Tone determines the blame target — derived from the game type
    match ctx.game_type {
        GameType::Horror  => {
            let opts = [format!("{} and nobody warned me", ev), format!("{} — this game set me up", ev)];
            opts[ctx.seed % opts.len()].clone()
        }
        GameType::Cozy    => {
            let opts = [format!("{} and it was entirely preventable", ev), format!("{} — the game did this on purpose", ev)];
            opts[ctx.seed % opts.len()].clone()
        }
        GameType::Social  => {
            let opts = [format!("{} and i know exactly whose fault that was", ev), format!("{} — trusting teammates was the first mistake", ev)];
            opts[ctx.seed % opts.len()].clone()
        }
        GameType::FPS => {
            let opts = [format!("{} and that was not a fair fight", ev), format!("{} — explain how that's balanced", ev)];
            opts[ctx.seed % opts.len()].clone()
        }
        GameType::Generic => {
            let opts = [format!("{}. somebody explain how that's okay", ev), format!("{}. i need answers", ev)];
            opts[ctx.seed % opts.len()].clone()
        }
    }
}

// ═══════════════════════════════════════════════════════════════════
//  Mode: Observation — third-person, dry
// ═══════════════════════════════════════════════════════════════════
//
//  Outside observer describing what happened. Detached. Factual.
//  No "i". No personal pronouns. Documentary tone.
//  The event is stated as observable fact — not felt, not reacted to.
//
//  Sentence built by framing event_summary as a documentable moment.
//  Seed selects the framing structure.

fn gen_observation(ctx: &CaptionCtx) -> String {
    let ev = &ctx.event_summary;

    match ctx.game_type {
        GameType::FPS     => {
            let opts = [format!("the play where {}. watch it back", ev), format!("frame by frame: {}", ev)];
            opts[ctx.seed % opts.len()].clone()
        }
        GameType::Horror  => {
            let opts = [format!("you can hear the panic when {}", ev), format!("the moment {}", ev)];
            opts[ctx.seed % opts.len()].clone()
        }
        GameType::Cozy    => {
            let opts = [format!("total destruction: {}", ev), format!("a quiet stream until {}", ev)];
            opts[ctx.seed % opts.len()].clone()
        }
        GameType::Social  => {
            let opts = [format!("the group the moment {}: silence", ev), format!("everyone watched {} happen", ev)];
            opts[ctx.seed % opts.len()].clone()
        }
        GameType::Generic => {
            let opts = [
                format!("the exact moment {}", ev),
                format!("{}. that's the whole clip", ev),
                format!("{} — in real time", ev),
            ];
            opts[ctx.seed % opts.len()].clone()
        }
    }
}

// ═══════════════════════════════════════════════════════════════════
//  Mode: Minimal — 1–3 word gut reaction
// ═══════════════════════════════════════════════════════════════════
//
//  Maximum density. Period energy.
//  The word is extracted FROM the event_summary — not a generic
//  mood word.  "missed the shot" → "missed."  "got ambushed" → "ambushed."
//  Always names what happened, just in one word.

fn gen_minimal(ctx: &CaptionCtx) -> String {
    // Minimal = short but COMPLETE phrase (3-6 words) that references clip content.
    // Never a single word. Always makes sense on its own.

    // If we have transcript, extract a short meaningful fragment
    if let Some(ref q) = ctx.quote {
        let short = extract_short_phrase(q, ctx.seed);
        if short.split_whitespace().count() >= 2 {
            return short;
        }
    }

    // Fall back to event summary — take first 4-6 words
    let ev_short = first_n_words(&ctx.event_summary, 5);

    match ctx.game_type {
        GameType::FPS     => format!("{} — gone", ev_short),
        GameType::Horror  => format!("{} — nope", ev_short),
        GameType::Cozy    => format!("{} — whoops", ev_short),
        GameType::Social  => format!("{} — really", ev_short),
        GameType::Generic => ev_short,
    }
}

/// Extract a short phrase (3-6 words) from transcript text.
/// Tries to find a punchy sentence fragment rather than a single word.
fn extract_short_phrase(text: &str, seed: usize) -> String {
    // Split on sentence boundaries
    let sentences: Vec<&str> = text.split(|c: char| c == '.' || c == '!' || c == '?')
        .map(|s| s.trim())
        .filter(|s| {
            let wc = s.split_whitespace().count();
            wc >= 2 && wc <= 8
        })
        .collect();

    if !sentences.is_empty() {
        let picked = sentences[seed % sentences.len()];
        // If short enough, use as-is; otherwise take first 6 words
        let words: Vec<&str> = picked.split_whitespace().take(6).collect();
        return words.join(" ").to_lowercase();
    }

    // No good sentences — take 3-5 content words from the text
    let skip: &[&str] = &[
        "the", "a", "an", "and", "or", "but", "in", "on", "at", "to",
        "of", "for", "with", "from", "um", "uh", "like", "so", "just",
    ];
    let content_words: Vec<&str> = text.split_whitespace()
        .filter(|w| {
            let clean = w.trim_matches(|c: char| !c.is_alphabetic()).to_lowercase();
            clean.len() >= 2 && !skip.contains(&clean.as_str())
        })
        .take(4)
        .collect();

    if content_words.len() >= 2 {
        content_words.join(" ").to_lowercase()
    } else {
        first_n_words(text, 4).to_lowercase()
    }
}

/// Extract the most impactful single word from an event summary.
/// Skips articles, prepositions, and low-information verbs.
fn extract_punch_word(summary: &str) -> &str {
    const SKIP: &[&str] = &[
        "the", "a", "an", "and", "or", "but", "in", "on", "at", "to",
        "of", "for", "with", "from", "was", "were", "is", "are",
        "that", "this", "it", "got", "went", "had", "out", "up",
        "no", "not", "just", "when", "then", "so", "too",
    ];

    for word in summary.split_whitespace() {
        let clean = word.trim_matches(|c: char| !c.is_alphabetic());
        if clean.len() >= 3 && !SKIP.contains(&clean.to_lowercase().as_str()) {
            return clean;
        }
    }

    // Fallback: first word
    summary.split_whitespace().next().unwrap_or("gone")
}

/// First N words of a string.
fn first_n_words(s: &str, n: usize) -> String {
    s.split_whitespace().take(n).collect::<Vec<_>>().join(" ")
}

// ═══════════════════════════════════════════════════════════════════
//  Variant assembly
// ═══════════════════════════════════════════════════════════════════

fn build_variants(ctx: CaptionCtx, hashtags: Vec<String>) -> PostCaptions {
    // for mode in modes: generate_caption(event_summary, mode)
    // Each mode gets its own seed so outputs don't correlate.
    let captions: Vec<CaptionVariant> = MODES.iter().enumerate().map(|(i, &mode)| {
        let mode_ctx = CaptionCtx {
            seed: ctx.seed.wrapping_mul(i as usize + 7),
            event_summary: ctx.event_summary.clone(),
            quote: ctx.quote.clone(),
            game_type: ctx.game_type,
        };
        let text = generate_caption(mode, &mode_ctx);
        CaptionVariant {
            mode: match mode {
                Mode::DirectQuote     => "direct_quote",
                Mode::Blame           => "blame",
                Mode::InternalThought => "internal_thought",
                Mode::Observation     => "observation",
                Mode::Minimal         => "minimal",
            }.into(),
            label: match mode {
                Mode::DirectQuote     => "Direct Quote",
                Mode::Blame           => "Blame",
                Mode::InternalThought => "Inner Thought",
                Mode::Observation     => "Observation",
                Mode::Minimal         => "Minimal",
            }.into(),
            text,
        }
    }).collect();

    // Legacy compat: first 3 captions fill casual/funny/hype
    let casual = captions.first().map(|c| c.text.clone()).unwrap_or_default();
    let funny  = captions.get(1).map(|c| c.text.clone()).unwrap_or_default();
    let hype   = captions.get(2).map(|c| c.text.clone()).unwrap_or_default();

    PostCaptions { captions, hashtags, source: "free".into(), casual, funny, hype }
}

// ═══════════════════════════════════════════════════════════════════
//  Genericness rejection
// ═══════════════════════════════════════════════════════════════════

const GENERIC_PHRASES: &[&str] = &[
    "this happened",
    "something happened",
    "a moment hit",
    "can't believe this",
    "caught on stream",
    "stream moment",
    "this clip",
    "this is a clip",
    "gaming moment",
    "this was crazy",
    "that was wild",
    "just happened",
    "it happened",
    "this is insane",
    "watch this",
    "you need to see this",
    "moment of the day",
    "clip of the day",
];

// ═══════════════════════════════════════════════════════════════════
//  Quote extraction
// ═══════════════════════════════════════════════════════════════════

fn strong_quote(transcript: Option<&str>) -> Option<String> {
    let text = transcript?.trim();
    if text.len() < 3 { return None; }
    let filler = ["like", "so", "um", "uh", "okay", "ok", "well"];
    let words: Vec<&str> = text.split_whitespace()
        .skip_while(|w| filler.contains(&w.to_lowercase().as_str()))
        .collect();
    if words.len() < 2 { return None; }

    // Take up to 20 words but try to end at a sentence boundary
    let taken: Vec<&str> = words.iter().take(20).copied().collect();
    let joined = taken.join(" ").to_lowercase();

    // Try to cut at a sentence boundary (. ! ?) to avoid mid-sentence truncation
    if let Some(pos) = joined.rfind(|c: char| c == '.' || c == '!' || c == '?') {
        let sentence = joined[..=pos].trim().to_string();
        if sentence.len() >= 5 {
            return Some(sentence);
        }
    }

    // No sentence boundary found — use all taken words (up to 20)
    Some(joined)
}

fn primary_event(tags: &[String]) -> Option<&'static str> {
    let has = |t: &str| tags.iter().any(|x| x == t);
    if has("jumpscare") || has("ambush") { return Some("ambush"); }
    if has("fight")       { return Some("fight"); }
    if has("explosion")   { return Some("explosion"); }
    if has("celebration") { return Some("clutch"); }
    if has("panic")       { return Some("panic"); }
    if has("frustration") { return Some("frustration"); }
    if has("disbelief")   { return Some("disbelief"); }
    if has("shock")       { return Some("shock"); }
    if has("hype")        { return Some("hype"); }
    if has("reaction")    { return Some("reaction"); }
    None
}

// ═══════════════════════════════════════════════════════════════════
//  Hashtags — tone + platform + streamer niche
// ═══════════════════════════════════════════════════════════════════
//
//  Strategy: 3 evergreen (platform-specific) + 2 niche (game + content).
//  Per the Phase 12 decision (section 9 of docs/PHASE12_PROMPT_DIFF.md),
//  hashtags are never LLM-generated — this function is the single source
//  of truth.
//
//  Back-compat: the old signature `build_hashtags(tags, tone)` is preserved
//  as a thin wrapper that delegates to `build_hashtags_v2` with
//  `Platform::Generic`, empty niche tags, and no game name. Existing
//  callers produce the same tag list they did before Wave 1 for that
//  default case, modulo ordering and the new evergreen set.

/// Backward-compat shim: produce hashtags with no platform/niche context.
/// Preserved so existing call sites (generate_with_seed, generate_from_parts,
/// build_hashtags_pub) keep working without modification in Wave 1.
fn build_hashtags(tags: &[String], tone: Tone) -> Vec<String> {
    build_hashtags_v2(tags, tone, Platform::Generic, &[], None)
}

/// Expanded hashtag builder — platform-aware, niche-aware.
///
/// Returns up to 5 hashtags:
/// - **3 evergreen** (from `platform.evergreen_hashtags()`)
/// - **1 game/tone niche** — game name (snake-cased) if present, else tone tag
/// - **1 content niche** — clutch / fail / jumpscare / or first of `streamer_niche_tags`
///
/// All output is lowercase, strip-non-alphanumeric, deduped, capped at 5.
pub fn build_hashtags_v2(
    tags: &[String],
    tone: Tone,
    platform: Platform,
    streamer_niche_tags: &[String],
    game_name: Option<&str>,
) -> Vec<String> {
    let mut out: Vec<String> = platform
        .evergreen_hashtags()
        .iter()
        .map(|s| s.to_string())
        .collect();

    // Niche slot 1: game name if present, else tone tag.
    let tone_tag = match tone {
        GameType::Horror  => "horrorgaming",
        GameType::Cozy    => "cozygaming",
        GameType::Social  => "partygame",
        GameType::FPS     => "fps",
        GameType::Generic => "clips",
    };
    if let Some(game) = game_name.map(sanitize_hashtag).filter(|g| !g.is_empty()) {
        out.push(game);
    } else {
        out.push(tone_tag.to_string());
    }

    // Niche slot 2: content-specific signal tag or first streamer-niche tag.
    let has = |t: &str| tags.iter().any(|x| x == t);
    if has("jumpscare") || has("ambush") {
        out.push("jumpscare".into());
    } else if has("celebration") || has("hype") {
        out.push("clutch".into());
    } else if has("frustration") || has("panic") {
        out.push("fail".into());
    } else if let Some(niche) = streamer_niche_tags.first().map(|s| sanitize_hashtag(s)) {
        if !niche.is_empty() {
            out.push(niche);
        }
    }

    // If we have headroom and a streamer-niche tag not yet included, append it.
    if out.len() < 5 {
        for niche in streamer_niche_tags.iter().skip(1) {
            let clean = sanitize_hashtag(niche);
            if !clean.is_empty() && !out.contains(&clean) {
                out.push(clean);
                if out.len() >= 5 {
                    break;
                }
            }
        }
    }

    out.dedup();
    out.truncate(5);
    out
}

/// Sanitize a string into a hashtag-safe form: lowercase, alphanumeric only,
/// no spaces. Empty if the input has no alphanumeric characters.
fn sanitize_hashtag(raw: &str) -> String {
    raw.chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .flat_map(|c| c.to_lowercase())
        .collect()
}

// ═══════════════════════════════════════════════════════════════════
//  LLM-based caption generation (BYOK)
// ═══════════════════════════════════════════════════════════════════
//
//  When a Claude API key is available, captions are generated by the
//  model instead of the pattern system.  One API call produces all 5
//  captions with mode-specific instructions.  Falls back to the
//  pattern system if the key is missing or the call fails.

/// System prompt shared by caption and title generation.
pub const LLM_SYSTEM_PROMPT: &str = "You are a gaming content creator writing captions for your own clips on TikTok, YouTube Shorts, and Instagram Reels. You have a sharp sense of humor, you're self-aware, and you talk like a real gamer \u{2014} not a brand account. You've watched the clip and you're writing about YOUR experience. First person. Lowercase is fine. You never use hashtags. You keep it under 280 characters.";

/// Human-readable label for each caption mode.
fn mode_label(mode: &str) -> &'static str {
    match mode {
        "direct_quote"     => "Quote",
        "blame"            => "Blame",
        "internal_thought" => "Thought",
        "observation"      => "Observe",
        "minimal"          => "Minimal",
        "punchy"           => "Punchy",
        "clean"            => "Clean",
        "funny"            => "Funny",
        "hype"             => "Hype",
        "search"           => "SEO",
        _ => "Caption",
    }
}

/// Instruction block describing a single tone, with examples.
fn tone_instruction(mode: &str) -> &'static str {
    match mode {
        "direct_quote"     => "TONE: Quote \u{2014} The transcript is your goldmine. Find the funniest or most dramatic line and use it FULLY \u{2014} don't chop it down to 3 words. Use enough of the quote so it's funny on its own. Then add a short reaction or framing. Examples: \"my friend really said 'what happened to gamers having shame' while I'm out here streaming at 2am\", \"'back in my day we had shame' \u{2014} sir this is Dead by Daylight\", \"he hit us with 'what happened to gamers' like we didn't already know\"",
        "blame"            => "TONE: Blame \u{2014} You're tilted. Blame your teammates, the game, the devs, matchmaking, your internet, your mouse, ANYTHING but yourself (or ironically blame yourself). Frustrated but funny. Examples: \"my team really watched that happen in 4k\", \"riot looked at my MMR and laughed\", \"i'm not bad the game is just better than me\", \"this is what peak matchmaking looks like apparently\"",
        "internal_thought" => "TONE: Thought \u{2014} Existential gamer moment. You're reflecting on what just happened like it changed you as a person. Dramatic, philosophical, a little unhinged. First person. Examples: \"i think about this play at 3am\", \"this is the moment i knew i peaked\", \"i've been staring at the ceiling since this happened\", \"some rounds teach you about yourself\"",
        "observation"      => "TONE: Observe \u{2014} You're narrating what happened like a nature documentary or a sports commentator. Third person or detached. Dry humor. Examples: \"man really walked into that like it was his first day\", \"the confidence followed by the immediate failure is poetic\", \"he said it with his whole chest too\", \"that was the exact wrong decision at the exact wrong time\"",
        "minimal"          => "TONE: Minimal \u{2014} 5 words or less. Gut punch. No explanation needed. The clip speaks for itself. Examples: \"nah.\", \"pain.\", \"we don't talk about this\", \"i'm done\", \"that's enough for today\"",
        "punchy"           => "TONE: Punchy \u{2014} High-energy, attention-grabbing, hard-hitting. Front-load the most exciting moment. Short sentences, strong verbs, zero filler. Focus on the ACTION that happened, not what was said. Examples: \"pushed through smoke and dropped all three\", \"one bullet. one kill. one tilted lobby.\", \"turned a 1v3 into a highlight reel\"",
        "clean"            => "TONE: Clean \u{2014} Polished, confident, no chaos. Write like a content creator who knows this clip is fire and doesn't need to oversell it. Calm energy, understated flex. Focus on the OUTCOME. Examples: \"calculated.\", \"clean rotations win rounds\", \"the read was right\", \"just another tuesday\"",
        "funny"            => "TONE: Funny \u{2014} Comedy first. Find the most absurd, ironic, or unexpected part of the clip and build the joke around THAT moment. Self-aware humor, exaggeration welcome. DON'T just quote \u{2014} add comedic framing. Examples: \"my game sense said go left. it lied.\", \"i peaked in 2019 and it's been downhill since\", \"the way i screamed and still died\"",
        "hype"             => "TONE: Hype \u{2014} Maximum energy. You're hyping yourself up. This is your best play and everyone needs to know. Bold, confident, slightly unhinged excitement. Focus on how INSANE the play was. Examples: \"DID THAT JUST HAPPEN?!\", \"i will never hit a shot like that again\", \"someone clip that. oh wait.\", \"that's the play of the year idc\"",
        "search"           => "TONE: SEO \u{2014} Written for discoverability. Include the game name, what happened, and searchable keywords naturally. Descriptive but still casual. Think: what would someone search to find this clip? Examples: \"insane valorant ace clutch 1v5 on haven\", \"dead by daylight killer rage quit after flashlight save\", \"overwatch 2 genji blade team wipe ranked\"",
        _ => "Write a short, punchy caption for this gaming clip.",
    }
}

/// Generate a single caption for a specific tone via the Claude/OpenAI/Gemini API.
///
/// Accepts the user's selected model from Settings instead of hardcoding one.
/// Only generates ONE caption for the requested tone — saves tokens and produces
/// better results since the model can focus.
pub async fn generate_llm(
    api_key: &str,
    model: &str,
    selected_mode: &str,
    event_summary: &str,
    transcript_quote: Option<&str>,
    tone_label: &str,
    tags: &[String],
    full_transcript: Option<&str>,
    clip_title: &str,
    game_name: Option<&str>,
) -> Result<Vec<CaptionVariant>, AppError> {
    // Build transcript section — prefer full subtitle transcript, fall back to single quote
    let transcript_section = if let Some(ft) = full_transcript.filter(|t| !t.trim().is_empty()) {
        // Truncate to ~800 chars to give Claude enough context about what happened
        let truncated = if ft.len() > 800 { &ft[..800] } else { ft };
        format!("TRANSCRIPT (what was said in the clip):\n\"{}\"\n\n", truncated)
    } else if let Some(q) = transcript_quote {
        format!("The person said: \"{}\"\n\n", q)
    } else {
        String::new()
    };

    let tag_line = if tags.is_empty() {
        String::new()
    } else {
        format!("Detected signals: {}\n", tags.join(", "))
    };

    let title_line = if clip_title.is_empty() {
        String::new()
    } else {
        format!("CLIP TITLE: {}\n", clip_title)
    };

    let game_line = match game_name {
        Some(name) if !name.is_empty() => {
            log::info!("[generate_llm] Game name received: {}", name);
            format!("GAME: {}\n", name)
        },
        _ => {
            log::info!("[generate_llm] No game name provided");
            String::new()
        },
    };

    let game_context = match game_name {
        Some(name) if !name.is_empty() => format!(" This is a {} clip — reference the game naturally where it fits.", name),
        _ => String::new(),
    };

    let game_style = match tone_label {
        "FPS / competitive shooter" => format!("Use competitive/tactical wording: pushed, dropped, one-tapped, rotated. Fast, clipped sentences.{}", game_context),
        "horror / survival" => format!("Use dread/survival wording: the dark, behind me, that noise, nope. Tense, breathless phrasing.{}", game_context),
        "cozy / chaotic casual" => format!("Use chaotic-wholesome wording: whoops, the kitchen, the plan, on fire. Light, exasperated phrasing.{}", game_context),
        "social / party / co-op" => format!("Use group-dynamics wording: the team, whose fault, trust broken, voted out. Accusatory, social phrasing.{}", game_context),
        _ => format!("Use plain streamer wording. No genre-specific flavor.{}", game_context),
    };

    let tone_block = tone_instruction(selected_mode);

    let prompt = format!(
        r#"Write ONE caption for my gaming clip.

GENRE: {tone}
{title}{game}WHAT HAPPENED: {event}
{transcript}{tags}
{tone_block}

STYLE GUIDE: {style}

RULES:
- Reference specific moments, dialogue, or reactions from the transcript — write like you watched the clip
- When quoting from the transcript, USE ENOUGH OF THE QUOTE for it to make sense and be funny. Don't chop a great line into 3 words. If someone said "what happened to gamers having shame doing this" — use the full line or close to it, not just "no shame"
- The caption should be specific to THIS clip — if someone reading the caption can't tell which clip it's from, it's too generic. Don't write captions that could apply to any random clip from the same game
- If the transcript has a funny, dramatic, or memorable line — that's your material. Build the caption around what was ACTUALLY SAID
- HARD LIMIT: 280 characters maximum. Count carefully. Most great captions are 80-180 characters. No hashtags. 1-2 emojis max (optional, only if natural)
- BANNED: "this happened", "caught on stream", "this was crazy", "just happened", "watch this", "you need to see this", "you won't believe", "check this out", "insane clip"

Respond with ONLY the caption. No quotes, no labels, nothing else."#,
        tone = tone_label,
        title = title_line,
        game = game_line,
        event = event_summary,
        transcript = transcript_section,
        tags = tag_line,
        tone_block = tone_block,
        style = game_style,
    );

    let client = reqwest::Client::new();
    let body = serde_json::json!({
        "model": model,
        "max_tokens": 256,
        "system": LLM_SYSTEM_PROMPT,
        "messages": [{
            "role": "user",
            "content": prompt,
        }]
    });

    log::debug!("Transcript being sent: \"{}\"", transcript_section.trim());
    log::debug!("Caption API Request:");
    log::debug!("Model: {}", model);
    log::debug!("Mode: {}", selected_mode);
    log::debug!("System: {}", LLM_SYSTEM_PROMPT);
    log::debug!("User message:\n{}", prompt);
    log::debug!("--- END Caption API Request ---");

    let resp = client
        .post("https://api.anthropic.com/v1/messages")
        .header("x-api-key", api_key)
        .header("anthropic-version", "2023-06-01")
        .header("content-type", "application/json")
        .json(&body)
        .send()
        .await
        .map_err(|e| AppError::Api(format!("Claude caption request failed: {e}")))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        return Err(AppError::Api(format!("Claude API {}: {}", status, &body[..body.len().min(200)])));
    }

    let resp_json: serde_json::Value = resp.json().await
        .map_err(|e| AppError::Api(format!("Failed to parse Claude response: {e}")))?;

    let text = resp_json["content"][0]["text"]
        .as_str()
        .ok_or_else(|| AppError::Api("No text in Claude response".into()))?
        .trim()
        .to_string();

    if text.is_empty() {
        return Err(AppError::Api("Claude returned empty caption".into()));
    }

    // Strip surrounding quotes if the model wrapped the caption in them
    let cleaned = text.trim_matches('"').trim_matches('\'').trim().to_string();

    // Hard-enforce 280 character limit — LLMs are bad at counting chars
    let enforced = if cleaned.chars().count() > 280 {
        // Try to truncate at the last sentence/phrase boundary before 280
        let truncated: String = cleaned.chars().take(277).collect();
        if let Some(pos) = truncated.rfind(|c: char| c == '.' || c == '!' || c == '?' || c == '\n') {
            truncated[..=pos].trim().to_string()
        } else if let Some(pos) = truncated.rfind(' ') {
            // No sentence end — break at last space and add ellipsis
            format!("{}…", truncated[..pos].trim())
        } else {
            format!("{}…", truncated.trim())
        }
    } else {
        cleaned
    };

    let label = mode_label(selected_mode).to_string();

    log::debug!("Caption RESULT — mode: {}, len: {}, text: \"{}\"", selected_mode, enforced.chars().count(), enforced);

    Ok(vec![CaptionVariant {
        mode: selected_mode.to_string(),
        label,
        text: enforced,
    }])
}

/// Generate a clip title via the Claude API.
///
/// Returns a single short, punchy title (max 60 chars) that a gaming
/// content creator would use.  Falls back to None on any failure.
pub async fn generate_llm_title(
    api_key: &str,
    model: &str,
    event_summary: &str,
    full_transcript: Option<&str>,
    tags: &[String],
    game_name: Option<&str>,
) -> Result<String, AppError> {
    let transcript_section = if let Some(ft) = full_transcript.filter(|t| !t.trim().is_empty()) {
        let truncated = if ft.len() > 800 { &ft[..800] } else { ft };
        format!("TRANSCRIPT:\n\"{}\"\n\n", truncated)
    } else {
        String::new()
    };

    // Randomly pick a title angle category each call so consecutive
    // regenerations explore different aspects of the clip.
    let angles = [
        ("REACTION", "Focus on the streamer's emotional reaction — shock, panic, disbelief, joy. Example style: \"my heart actually stopped\""),
        ("GAMEPLAY", "Focus on what physically happened in the game — the play, the kill, the fail. Example style: \"jumped into a 1v3 and somehow lived\""),
        ("QUOTE", "Use or paraphrase a funny/memorable line from the transcript. Example style: \"back in my day gamers had honor\""),
        ("ABSURDITY", "Focus on how ridiculous or unexpected the situation was. Example style: \"streaming at 2am was a mistake\""),
        ("HOOK", "Write a dramatic hook that creates curiosity — make people NEED to watch. Example style: \"wait for the ending\" or \"this should not have worked\""),
        ("SELF-DEPRECATING", "Self-deprecating humor from the streamer's perspective. Example style: \"this is why i'm hardstuck\" or \"i deserve this\""),
    ];

    use std::time::SystemTime;
    let seed = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .map(|d| d.as_nanos() as usize)
        .unwrap_or(0);
    let (angle_name, angle_desc) = angles[seed % angles.len()];

    // Also pick a random transcript word to explicitly ban, further
    // preventing the model from fixating on one dominant theme.
    let avoid_word = full_transcript
        .filter(|t| !t.trim().is_empty())
        .and_then(|t| {
            let words: Vec<&str> = t.split_whitespace()
                .filter(|w| w.len() >= 4)
                .map(|w| w.trim_matches(|c: char| !c.is_alphanumeric()))
                .filter(|w| !w.is_empty())
                .collect();
            if words.is_empty() {
                None
            } else {
                // Use a different part of the seed so it doesn't correlate with angle selection
                Some(words[(seed / 7) % words.len()].to_lowercase())
            }
        });

    let avoid_line = match &avoid_word {
        Some(word) if !word.is_empty() => format!(
            "BANNED WORD: Do NOT use the word \"{}\" or synonyms of it in your title.\n",
            word
        ),
        _ => String::new(),
    };

    let tag_line = if tags.is_empty() {
        String::new()
    } else {
        format!("Viral signals: {}\n", tags.join(", "))
    };

    let game_line = match game_name {
        Some(name) if !name.is_empty() => format!("GAME: {}\n", name),
        _ => String::new(),
    };

    let prompt = format!(
        r#"Generate ONE short punchy title (max 60 characters) for this gaming clip.

{game}WHAT HAPPENED: {event}
{transcript}{tags}
YOUR ANGLE FOR THIS TITLE: {angle_name}
{angle_desc}

You MUST write the title from the {angle_name} angle described above. Do NOT default to summarizing the transcript's most obvious theme.
{avoid}
RULES:
- Maximum 60 characters. Shorter is better.
- Write like a real gaming content creator — lowercase is fine, be casual.
- No hashtags, no emojis, no clickbait phrases like "you won't believe".
- No ALL CAPS.
- The title should make someone want to click.

Respond with ONLY the title. No quotes, no explanation — just the title text."#,
        game = game_line,
        event = event_summary,
        transcript = transcript_section,
        tags = tag_line,
        angle_name = angle_name,
        angle_desc = angle_desc,
        avoid = avoid_line,
    );

    let client = reqwest::Client::new();
    let body = serde_json::json!({
        "model": model,
        "max_tokens": 80,
        "system": LLM_SYSTEM_PROMPT,
        "messages": [{
            "role": "user",
            "content": prompt,
        }]
    });

    log::debug!("Title API Request (angle: {}, avoid: {:?}):", angle_name, avoid_word);
    log::debug!("Model: {}", model);
    log::debug!("System: {}", LLM_SYSTEM_PROMPT);
    log::debug!("User message:\n{}", prompt);
    log::debug!("--- END Title API Request ---");

    let resp = client
        .post("https://api.anthropic.com/v1/messages")
        .header("x-api-key", api_key)
        .header("anthropic-version", "2023-06-01")
        .header("content-type", "application/json")
        .json(&body)
        .send()
        .await
        .map_err(|e| AppError::Api(format!("Claude title request failed: {e}")))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();
        return Err(AppError::Api(format!("Claude API {}: {}", status, &body[..body.len().min(200)])));
    }

    let resp_json: serde_json::Value = resp.json().await
        .map_err(|e| AppError::Api(format!("Failed to parse Claude title response: {e}")))?;

    let text = resp_json["content"][0]["text"]
        .as_str()
        .ok_or_else(|| AppError::Api("No text in Claude title response".into()))?
        .trim()
        .to_string();

    if text.is_empty() {
        return Err(AppError::Api("Claude returned empty title".into()));
    }

    // Strip surrounding quotes if the model wrapped it
    let cleaned = text.trim_matches('"').trim_matches('\'').trim().to_string();

    // Enforce 60 char limit
    let final_title = if cleaned.chars().count() > 60 {
        let truncated: String = cleaned.chars().take(60).collect();
        if let Some(space) = truncated.rfind(' ') {
            truncated[..space].to_string()
        } else {
            truncated
        }
    } else {
        cleaned
    };

    log::debug!("Title RESULT — len: {}, text: \"{}\"", final_title.chars().count(), final_title);

    Ok(final_title)
}

// ═══════════════════════════════════════════════════════════════════
//  Public wrappers for lib.rs to call into private helpers
// ═══════════════════════════════════════════════════════════════════

/// Public re-export of GameType (aliased as Tone for backward compat).
pub type TonePub = GameType;

/// Public game type detection — primary API.
pub fn detect_game_type_pub(
    tags: &[String], transcript: Option<&str>,
    audio: f64, speech: f64, scene: f64,
) -> GameType {
    detect_game_type(tags, transcript, audio, speech, scene)
}

/// Backward-compat wrapper.
pub fn classify_tone_pub(
    tags: &[String], transcript: Option<&str>,
    audio: f64, speech: f64, scene: f64,
) -> GameType {
    detect_game_type(tags, transcript, audio, speech, scene)
}

pub fn primary_event_pub(tags: &[String]) -> Option<&'static str> {
    primary_event(tags)
}

pub fn synthesize_event_pub(event: Option<&str>, tone: Tone, tags: &[String], seed: usize) -> String {
    synthesize_event(event, tone, tags, seed)
}

/// Public re-export: generate event summary from parts (for lib.rs / Tauri commands).
pub fn generate_event_summary_from_parts(
    tags: &[String],
    transcript: Option<&str>,
    audio_score: f64,
    speech_score: f64,
    scene_score: f64,
    start_time: f64,
) -> String {
    let event = primary_event(tags);
    let tone = classify_tone(tags, transcript, audio_score, speech_score, scene_score);
    transcript_action_summary(transcript, event, tags, tone)
        .unwrap_or_else(|| synthesize_event(event, tone, tags, start_time as usize))
}

pub fn strong_quote_pub(transcript: Option<&str>) -> Option<String> {
    strong_quote(transcript)
}

pub fn build_hashtags_pub(tags: &[String], tone: Tone) -> Vec<String> {
    build_hashtags(tags, tone)
}

// ═══════════════════════════════════════════════════════════════════
//  Tests
// ═══════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pipeline::{ClipScoreBreakdown, SignalType};

    fn make_clip(tags: &[&str], audio: f64, speech: f64, scene: f64) -> CandidateClip {
        let mut c = CandidateClip::new(
            60.0, 85.0,
            ClipScoreBreakdown::new(audio, speech, scene, None),
            vec![SignalType::Audio, SignalType::Transcript],
        );
        c.tags = tags.iter().map(|s| s.to_string()).collect();
        c
    }

    // ── Tone classification ──

    #[test]
    fn horror_from_jumpscare_tag() {
        assert_eq!(
            classify_tone(&["jumpscare".into()], None, 0.8, 0.5, 0.6),
            GameType::Horror,
        );
    }

    #[test]
    fn shooter_from_fight_tag() {
        assert_eq!(
            classify_tone(&["fight".into(), "ambush".into()], None, 0.8, 0.3, 0.7),
            GameType::FPS,
        );
    }

    #[test]
    fn social_from_speech_heavy_signals() {
        assert_eq!(
            classify_tone(&["reaction".into(), "hype".into()], None, 0.3, 0.8, 0.2),
            GameType::Social,
        );
    }

    #[test]
    fn horror_from_transcript() {
        assert_eq!(
            classify_tone(&[], Some("oh god he's behind you run"), 0.5, 0.5, 0.5),
            GameType::Horror,
        );
    }

    #[test]
    fn cozy_from_transcript() {
        assert_eq!(
            classify_tone(&[], Some("whoops the kitchen is on fire"), 0.5, 0.5, 0.3),
            GameType::Cozy,
        );
    }

    #[test]
    fn social_from_transcript() {
        assert_eq!(
            classify_tone(&[], Some("why did you do that to our team"), 0.4, 0.6, 0.3),
            GameType::Social,
        );
    }

    // ── Tone affects output ──

    #[test]
    fn horror_captions_reference_event() {
        let mut clip = make_clip(&["jumpscare", "panic"], 0.8, 0.6, 0.5);
        clip.transcript_excerpt = Some("Oh no oh no".into());
        clip.title = Some("Jumpscare detected".into());
        let captions = generate(&clip);
        let all = format!("{} {} {}", captions.casual, captions.funny, captions.hype).to_lowercase();
        // Captions should reference the specific event, not be generic
        assert!(
            all.contains("ambush") || all.contains("panic") || all.contains("jump")
            || all.contains("oh no") || all.contains("scar") || all.contains("corner")
            || all.contains("dark") || all.contains("noise"),
            "horror captions should reference the event: {all}"
        );
        // Should NOT be totally generic
        assert!(
            !all.contains("something happened") && !all.contains("gaming moment"),
            "horror captions should not be generic: {all}"
        );
    }

    #[test]
    fn shooter_captions_reference_event() {
        let mut clip = make_clip(&["fight", "ambush"], 0.9, 0.3, 0.7);
        clip.title = Some("Fight goes wrong fast".into());
        let captions = generate(&clip);
        let all = format!("{} {} {}", captions.casual, captions.funny, captions.hype).to_lowercase();
        // Captions must reference the specific event
        assert!(
            all.contains("rush") || all.contains("fight") || all.contains("ambush")
            || all.contains("push") || all.contains("warning") || all.contains("guard")
            || all.contains("wrong") || all.contains("dropped"),
            "shooter captions should reference the event: {all}"
        );
        assert!(
            !all.contains("something happened") && !all.contains("gaming moment"),
            "should not be generic: {all}"
        );
    }

    #[test]
    fn horror_hashtags_include_horrorgaming() {
        let clip = make_clip(&["jumpscare"], 0.8, 0.5, 0.6);
        let captions = generate(&clip);
        assert!(captions.hashtags.contains(&"horrorgaming".to_string()));
    }

    // ── Existing contract tests ──

    #[test]
    fn generates_three_variants() {
        let mut clip = make_clip(&["fight", "panic"], 0.8, 0.6, 0.4);
        clip.title = Some("Fight turns bad fast".into());
        clip.transcript_excerpt = Some("Oh no what is happening".into());
        let captions = generate(&clip);
        assert!(!captions.casual.is_empty());
        assert!(!captions.funny.is_empty());
        assert!(!captions.hype.is_empty());
    }

    #[test]
    fn variants_are_different() {
        let mut clip = make_clip(&["ambush", "shock"], 0.8, 0.7, 0.5);
        clip.title = Some("Ambush out of nowhere".into());
        clip.transcript_excerpt = Some("What the heck just happened to me".into());
        let captions = generate(&clip);
        assert_ne!(captions.casual, captions.funny);
        assert_ne!(captions.casual, captions.hype);
        assert_ne!(captions.funny, captions.hype);
    }

    #[test]
    fn no_transcript_still_works() {
        let mut clip = make_clip(&["fight"], 0.8, 0.0, 0.4);
        clip.title = Some("Fight goes wrong fast".into());
        let captions = generate(&clip);
        assert!(!captions.casual.is_empty());
        assert!(!captions.funny.is_empty());
        assert!(!captions.hype.is_empty());
    }

    #[test]
    fn no_tags_still_works() {
        let mut clip = make_clip(&[], 0.5, 0.3, 0.2);
        clip.title = Some("Audio peak at 1:00".into());
        let captions = generate(&clip);
        assert!(!captions.casual.is_empty());
    }

    #[test]
    fn hashtags_include_gaming_and_fyp() {
        let clip = make_clip(&["jumpscare", "reaction"], 0.8, 0.6, 0.4);
        let captions = generate(&clip);
        assert!(captions.hashtags.contains(&"gaming".to_string()));
        assert!(captions.hashtags.contains(&"fyp".to_string()));
    }

    #[test]
    fn hashtags_capped_at_five() {
        let clip = make_clip(
            &["jumpscare", "fight", "celebration", "frustration", "reaction", "shock"],
            0.9, 0.8, 0.7,
        );
        let captions = generate(&clip);
        assert!(captions.hashtags.len() <= 5);
    }

    #[test]
    fn captions_are_short() {
        let mut clip = make_clip(&["ambush", "panic"], 0.8, 0.7, 0.5);
        clip.transcript_excerpt = Some("Oh my god what just happened right now".into());
        clip.title = Some("Ambush hits and panic sets in".into());
        let captions = generate(&clip);
        for (name, text) in [("casual", &captions.casual), ("funny", &captions.funny), ("hype", &captions.hype)] {
            let wc = text.split_whitespace().count();
            assert!(wc <= 16, "{name} too long ({wc} words): {text}");
        }
    }

    #[test]
    fn no_banned_hype_words() {
        let mut clip = make_clip(&["fight", "shock", "hype", "celebration"], 0.9, 0.8, 0.7);
        clip.transcript_excerpt = Some("That was the best play I have ever seen in my life".into());
        clip.title = Some("Clutch play at the last second".into());
        let captions = generate(&clip);
        let all = format!("{} {} {}", captions.casual, captions.funny, captions.hype).to_lowercase();
        for banned in ["insane", "unbelievable", "crazy", "you won't believe", "mind-blowing"] {
            assert!(!all.contains(banned), "found banned word '{}' in: {}", banned, all);
        }
    }

    // ── Event summary tests ──

    #[test]
    fn event_summary_uses_transcript_action() {
        let mut clip = make_clip(&["fight", "frustration"], 0.8, 0.6, 0.4);
        clip.transcript_excerpt = Some("I missed that shot are you kidding me".into());
        let summary = generate_event_summary(&clip);
        assert!(summary.contains("missed"), "should extract 'missed': {}", summary);
        assert!(summary.contains("fight"), "should mention fight context: {}", summary);
    }

    #[test]
    fn event_summary_transcript_with_death() {
        let mut clip = make_clip(&["fight", "panic"], 0.8, 0.6, 0.4);
        clip.transcript_excerpt = Some("Oh no I died again this is so bad".into());
        let summary = generate_event_summary(&clip);
        assert!(summary.contains("died"), "should extract 'died': {}", summary);
    }

    #[test]
    fn event_summary_falls_back_to_tags_on_exclamations() {
        let mut clip = make_clip(&["ambush", "panic"], 0.8, 0.6, 0.4);
        clip.transcript_excerpt = Some("Oh no oh no".into());
        let summary = generate_event_summary(&clip);
        // "Oh no" is too short (< 3 words after trim) — falls back to tag synthesis
        assert!(
            summary.contains("ambush") || summary.contains("panic") || summary.contains("jumped"),
            "should use tag-based synthesis: {}", summary
        );
    }

    #[test]
    fn event_summary_no_transcript_uses_tags() {
        let clip = make_clip(&["fight", "celebration"], 0.8, 0.5, 0.4);
        let summary = generate_event_summary(&clip);
        assert!(
            summary.contains("fight") || summary.contains("clutch") || summary.contains("won") || summary.contains("survived"),
            "should reference fight+celebration: {}", summary
        );
    }

    #[test]
    fn event_summary_no_signals_still_works() {
        let clip = make_clip(&[], 0.3, 0.2, 0.1);
        let summary = generate_event_summary(&clip);
        assert!(!summary.is_empty(), "should always produce a summary");
    }

    #[test]
    fn event_summary_with_scared_transcript() {
        let mut clip = make_clip(&["jumpscare"], 0.8, 0.6, 0.5);
        clip.transcript_excerpt = Some("I just got so scared what was that".into());
        let summary = generate_event_summary(&clip);
        assert!(summary.contains("scared"), "should extract 'scared': {}", summary);
    }

    #[test]
    fn event_summary_whiff_in_transcript() {
        let mut clip = make_clip(&["fight"], 0.7, 0.5, 0.3);
        clip.transcript_excerpt = Some("I whiffed that so hard what am I doing".into());
        let summary = generate_event_summary(&clip);
        assert!(summary.contains("whiff"), "should extract 'whiffed': {}", summary);
    }

    #[test]
    fn captions_reference_event_summary() {
        let mut clip = make_clip(&["fight", "frustration"], 0.8, 0.6, 0.4);
        clip.transcript_excerpt = Some("I missed that shot completely".into());
        let captions = generate(&clip);
        let all_text: String = captions.captions.iter()
            .map(|c| c.text.to_lowercase())
            .collect::<Vec<_>>()
            .join(" ");
        // At least one caption should reference the event
        assert!(
            all_text.contains("miss") || all_text.contains("fight") || all_text.contains("shot")
            || all_text.contains("wrong") || all_text.contains("fault") || all_text.contains("lost"),
            "captions should reference the event: {}", all_text
        );
    }

    // ── GameType detection ──

    #[test]
    fn detect_fps_from_fight_tags() {
        assert_eq!(
            detect_game_type(&["fight".into()], None, 0.8, 0.3, 0.7),
            GameType::FPS,
        );
    }

    #[test]
    fn detect_generic_from_no_signals() {
        assert_eq!(
            detect_game_type(&[], None, 0.3, 0.3, 0.3),
            GameType::Generic,
        );
    }

    // ── GameType affects caption output ──

    #[test]
    fn fps_and_horror_produce_different_captions() {
        // Same event summary, different game types → different captions
        let ev = "got ambushed out of nowhere";
        let fps = generate_from_parts(
            &["fight".into(), "ambush".into()], None, "", 60.0, 0.8, 0.3, 0.7, 0,
        );
        let horror = generate_from_parts(
            &["jumpscare".into(), "ambush".into()], None, "", 60.0, 0.8, 0.3, 0.7, 0,
        );

        // DirectQuote should differ (FPS: "no shot—" vs Horror: "oh god—")
        let fps_quote = &fps.captions[0].text;
        let horror_quote = &horror.captions[0].text;
        assert_ne!(fps_quote, horror_quote,
            "FPS and Horror direct quotes should differ:\n  FPS: {}\n  Horror: {}", fps_quote, horror_quote);

        // Blame should differ (FPS: "not a fair fight" vs Horror: "nobody warned me")
        let fps_blame = &fps.captions[1].text;
        let horror_blame = &horror.captions[1].text;
        assert_ne!(fps_blame, horror_blame,
            "FPS and Horror blame should differ:\n  FPS: {}\n  Horror: {}", fps_blame, horror_blame);
    }

    #[test]
    fn cozy_captions_have_cozy_flavor() {
        let captions = generate_from_parts(
            &["explosion".into(), "celebration".into()], Some("whoops the kitchen"), "",
            60.0, 0.5, 0.5, 0.3, 0,
        );
        let all_text: String = captions.captions.iter()
            .map(|c| c.text.to_lowercase())
            .collect::<Vec<_>>()
            .join(" ");
        // Cozy flavor: should contain cozy-specific language
        assert!(
            all_text.contains("whoops") || all_text.contains("preventable")
            || all_text.contains("destruction") || all_text.contains("expect")
            || all_text.contains("kitchen"),
            "cozy captions should have cozy flavor: {}", all_text
        );
    }

    #[test]
    fn social_blame_targets_the_group() {
        let captions = generate_from_parts(
            &["reaction".into(), "hype".into()], Some("why did you do that to the team"), "",
            60.0, 0.3, 0.8, 0.2, 0,
        );
        let blame = &captions.captions[1].text.to_lowercase();
        assert!(
            blame.contains("fault") || blame.contains("team") || blame.contains("whose"),
            "social blame should target the group: {}", blame
        );
    }

    #[test]
    fn minimal_uses_event_word_not_generic() {
        let captions = generate_from_parts(
            &["fight".into(), "frustration".into()], Some("I missed that shot"), "",
            60.0, 0.8, 0.6, 0.4, 0,
        );
        let minimal = &captions.captions[4].text.to_lowercase();
        // Should contain an event-derived word, not a generic mood word
        assert!(
            minimal.contains("missed") || minimal.contains("fight") || minimal.contains("shot")
            || minimal.contains("lost") || minimal.contains("wrong"),
            "minimal should use event word: {}", minimal
        );
    }

    #[test]
    fn game_type_label_round_trips() {
        assert_eq!(GameType::FPS.label(), "FPS / competitive shooter");
        assert_eq!(GameType::Horror.label(), "horror / survival");
        assert_eq!(GameType::Cozy.label(), "cozy / chaotic casual");
        assert_eq!(GameType::Social.label(), "social / party / co-op");
        assert_eq!(GameType::Generic.label(), "general gaming");
    }

    // ── build_hashtags_v2 (Wave 1) ────────────────────────────────

    #[test]
    fn v2_backcompat_matches_old_behavior_for_generic_platform() {
        // Old wrapper should produce evergreen + tone-tag + content-tag shape
        let tags = vec!["jumpscare".into()];
        let out = build_hashtags(&tags, GameType::Horror);
        assert!(out.contains(&"gaming".to_string()));
        assert!(out.contains(&"horrorgaming".to_string()));
        assert!(out.contains(&"jumpscare".to_string()));
        assert!(out.len() <= 5);
    }

    #[test]
    fn v2_tiktok_evergreen_matches_platform() {
        let out = build_hashtags_v2(&[], GameType::Generic, Platform::TikTok, &[], None);
        // TikTok evergreen: gaming, fyp, gamingtiktok
        assert!(out.contains(&"gaming".to_string()));
        assert!(out.contains(&"fyp".to_string()));
        assert!(out.contains(&"gamingtiktok".to_string()));
    }

    #[test]
    fn v2_game_name_takes_niche_slot_one() {
        let out = build_hashtags_v2(
            &[],
            GameType::FPS,
            Platform::TikTok,
            &[],
            Some("Valorant"),
        );
        assert!(out.contains(&"valorant".to_string()), "expected valorant in {:?}", out);
        // Tone tag "fps" should be displaced by the game name
        assert!(!out.contains(&"fps".to_string()) || out.len() == 5);
    }

    #[test]
    fn v2_tone_tag_used_when_no_game_name() {
        let out = build_hashtags_v2(
            &[],
            GameType::Horror,
            Platform::TikTok,
            &[],
            None,
        );
        assert!(out.contains(&"horrorgaming".to_string()));
    }

    #[test]
    fn v2_streamer_niche_fills_content_slot_when_no_event_tag() {
        let out = build_hashtags_v2(
            &[],
            GameType::FPS,
            Platform::TikTok,
            &vec!["radiant".into(), "aimlab".into()],
            Some("Valorant"),
        );
        assert!(out.contains(&"radiant".to_string()));
    }

    #[test]
    fn v2_event_tag_wins_over_streamer_niche() {
        // When a content-specific event tag (jumpscare) is present,
        // it wins over streamer-niche tags for niche slot 2.
        let out = build_hashtags_v2(
            &["jumpscare".into()],
            GameType::Horror,
            Platform::TikTok,
            &vec!["radiant".into()],
            None,
        );
        assert!(out.contains(&"jumpscare".to_string()));
    }

    #[test]
    fn v2_always_caps_at_five() {
        let out = build_hashtags_v2(
            &["jumpscare".into(), "celebration".into()],
            GameType::Horror,
            Platform::TikTok,
            &vec!["radiant".into(), "aimlab".into(), "omen".into()],
            Some("Valorant"),
        );
        assert!(out.len() <= 5, "got {:?}", out);
    }

    #[test]
    fn v2_sanitize_hashtag_strips_spaces_and_symbols() {
        assert_eq!(sanitize_hashtag("Dead by Daylight"), "deadbydaylight");
        assert_eq!(sanitize_hashtag("Counter-Strike 2"), "counterstrike2");
        assert_eq!(sanitize_hashtag("#FYP!"), "fyp");
        assert_eq!(sanitize_hashtag(""), "");
        assert_eq!(sanitize_hashtag("   "), "");
    }

    #[test]
    fn v2_different_platforms_produce_different_evergreens() {
        let tiktok = build_hashtags_v2(&[], GameType::Generic, Platform::TikTok, &[], None);
        let shorts = build_hashtags_v2(&[], GameType::Generic, Platform::YouTubeShorts, &[], None);
        assert!(tiktok.contains(&"fyp".to_string()));
        assert!(shorts.contains(&"shorts".to_string()));
        assert_ne!(tiktok, shorts);
    }
}
