name = "clipgoblin-auth-proxy"
main = "src/index.js"
compatibility_date = "2026-07-12"

[observability]
enabled = true

[vars]
TWITCH_CLIENT_ID = "i734ser5qcdf8grvlllx6yzprwegfr"
YOUTUBE_CLIENT_ID = "963785158873-iuutl54610isuch1mcaqnbsoc90acrnb.apps.googleusercontent.com"
TIKTOK_CLIENT_KEY = "awzco3f3mgjpwjam"

[[ratelimits]]
name = "OAUTH_RATE_LIMITER"
namespace_id = "1001"
[ratelimits.simple]
limit = 30
period = 60

[[ratelimits]]
name = "OAUTH_GLOBAL_RATE_LIMITER"
namespace_id = "1002"
[ratelimits.simple]
limit = 300
period = 60
